# Generated by Django 5.2.7 on 2025-11-25 09:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='اسم المؤثر')),
                ('slug', models.SlugField(blank=True, help_text='سيتم إنشاؤه تلقائياً من اسم المؤثر', max_length=250, unique=True, verbose_name='الرابط الفريد')),
                ('platform', models.CharField(choices=[('instagram', 'إنستغرام'), ('tiktok', 'تيك توك'), ('youtube', 'يوتيوب'), ('snapchat', 'سناب شات'), ('twitter', 'تويتر'), ('other', 'أخرى')], max_length=50, verbose_name='المنصة الرئيسية')),
                ('custom_platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='منصة مخصصة')),
                ('username', models.CharField(help_text='اسم المستخدم في المنصة (مثال: @username)', max_length=200, verbose_name='اسم المستخدم')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='رابط الملف الشخصي')),
                ('followers_count', models.IntegerField(default=0, verbose_name='عدد المتابعين')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل')),
                ('prizes', models.JSONField(default=list, verbose_name='الجوائز')),
                ('colors', models.JSONField(default=list, verbose_name='الألوان')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مُوافق عليه'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('inactive', 'غير نشط')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('profile_image_url', models.URLField(blank=True, null=True, verbose_name='رابط صورة الملف الشخصي')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مؤثر',
                'verbose_name_plural': 'المؤثرون',
                'ordering': ['-created_at'],
            },
        ),
    ]
