# Generated by Django 5.2.7 on 2025-11-28 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('social_media_account', models.CharField(help_text='مثال: @username', max_length=200, verbose_name='حساب التواصل الاجتماعي')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='influencers.influencer', verbose_name='المؤثر')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['-created_at'],
            },
        ),
    ]
