# Generated by Django 5.2.7 on 2025-10-15 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='اسم الزائر')),
                ('prize', models.CharField(max_length=200, verbose_name='الجائزة')),
                ('won', models.BooleanField(default=True, verbose_name='فاز')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدورة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'دورة لعبة',
                'verbose_name_plural': 'دورات الألعاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
