# Generated by Django 5.2.7 on 2025-10-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamespin',
            name='visitor_phone',
            field=models.CharField(default='0000000000', help_text='رقم الجوال السعودي (مثال: 0501234567)', max_length=15, verbose_name='رقم الجوال'),
        ),
    ]
