# Generated by Django 5.2.7 on 2025-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamespin_visitor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamespin',
            name='visitor_phone',
            field=models.CharField(blank=True, help_text='رقم الجوال السعودي (مثال: 0501234567) - اختياري', max_length=15, null=True, verbose_name='رقم الجوال'),
        ),
    ]
