# Generated by Django 5.2.7 on 2025-10-15 16:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='اسم الجهة')),
                ('type', models.CharField(choices=[('restaurant', 'مطعم'), ('resort', 'منتجع'), ('hotel', 'فندق'), ('coffee', 'كوفي'), ('cafe', 'مقهى'), ('event', 'فعالية'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الجهة')),
                ('custom_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع مخصص')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل')),
                ('prizes', models.JSONField(default=list, verbose_name='الجوائز')),
                ('colors', models.JSONField(default=list, verbose_name='الألوان')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مُوافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='رابط الشعار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
