# Generated by Django 5.2.7 on 2025-10-16 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activation_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت نهاية التفعيل'),
        ),
        migrations.AddField(
            model_name='company',
            name='activation_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بداية التفعيل'),
        ),
        migrations.AddField(
            model_name='company',
            name='active_hours',
            field=models.IntegerField(default=24, help_text='من 1 إلى 24 ساعة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='عدد ساعات التفعيل'),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text='سيتم إنشاؤه تلقائياً من اسم الجهة', max_length=250, unique=True, verbose_name='الرابط الفريد'),
        ),
    ]
