# Generated by Django 5.2.7 on 2025-10-19 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_activation_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='الاثنين')),
                ('tuesday', models.BooleanField(default=False, verbose_name='الثلاثاء')),
                ('wednesday', models.BooleanField(default=False, verbose_name='الأربعاء')),
                ('thursday', models.BooleanField(default=False, verbose_name='الخميس')),
                ('friday', models.BooleanField(default=False, verbose_name='الجمعة')),
                ('saturday', models.BooleanField(default=False, verbose_name='السبت')),
                ('sunday', models.BooleanField(default=False, verbose_name='الأحد')),
                ('start_hour', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], default=0, help_text='الساعة من 0 (منتصف الليل) إلى 23 (11 مساءً)', verbose_name='ساعة البداية')),
                ('end_hour', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], default=23, help_text='الساعة من 0 (منتصف الليل) إلى 23 (11 مساءً)', verbose_name='ساعة النهاية')),
                ('duration_hours', models.IntegerField(default=24, help_text='عدد الساعات التي يبقى فيها الحساب مفعلاً (من 1 إلى 168 ساعة)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='عدد ساعات التفعيل')),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل أو إيقاف الجدولة التلقائية', verbose_name='الجدولة مفعلة')),
                ('last_activation', models.DateTimeField(blank=True, null=True, verbose_name='آخر تفعيل')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'جدولة التفعيل',
                'verbose_name_plural': 'جداول التفعيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
