# Generated by Django 5.2.7 on 2025-11-02 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_activationschedule_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_hours',
            field=models.IntegerField(default=1, help_text='من 1 إلى 168 ساعة (أسبوع كامل)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='عدد ساعات التفعيل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مُوافق عليه'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('scheduled', 'مجدول'), ('inactive', 'غير نشط')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
